### ISSUE TITLE
Support for new directory 

### ISSUE THREAD

**Issue by hc3188** [jsoma/bottlejack#14]
I downloaded the example folder from Slack and had it in my downloads. I edited a bunch of stuff and then moved it onto my desktop. Apparently, this wasn't a good idea because I get the following error when trying to open my CSS and HBS files: 

Unable to resolve non-existing file '/Users/harrisonconnery/Downloads/new_example/content'

Does anyone know how to resolve this?

**Comment by jsoma** [comment]
Maybe you moved it, but your terminal is still in the old directory? Give a look at updating - https://github.com/jsoma/bottlejack#updating - and it'll give you some debug info while you're running it to help see what's going on (especially if you add `--debug`).
