### ISSUE TITLE
Publishing the Website

### ISSUE THREAD

**Issue by fazilkhan** [jsoma/bottlejack#15]
Not being able to publish the website on github. Followed the portfolio autopublish steps but it breaks at the build site stage.  I set up the workflow as it was in portfolio autopublish, made a requirements.txt and update.py, changed the templates to gdoc.hbs and home.hbs within that but it still doesn’t work.

How is this process different. It would be great to have a walkthrough.

**Comment by jsoma** [comment]
Addressed here: https://github.com/jsoma/bottlejack#publishing

**Comment by hc3188** [comment]
FYI when doing this I had to push all the files again, not just docs. In case it's helpful for anyone down the road!
