### ISSUE TITLE
Navigation misfire

### ISSUE THREAD

**Issue by AFarence** [jsoma/bottlejack#18]
While attempting to navigate to projects or the home page via links, an interstatial webpage appears. This can be fixed by adding `/index.html` on line 49 in `gdoc.hbs` and line 49 of `home.hbs`

Image of navigation misfire below:
![image](https://user-images.githubusercontent.com/83982643/120248580-c646e900-c245-11eb-846a-b0b9caf62abe.png)

**Comment by jsoma** [comment]
So! We can talk about this in class, but that only happens then you are
running things locally - if you push it up to GitHub pages it'll
automatically go to index.html!

**Comment by AFarence** [comment]
Should I remove the instances of `index.html` I added then?

**Comment by jsoma** [comment]
yup, `index.html` gets done automatically!
