### ISSUE TITLE
Showcasing Work hosted outside of Github

### ISSUE THREAD

**Issue by fazilkhan** [jsoma/bottlejack#19]
Could we please have some update through which we are able to have a story on the portfolio homepage that opens on a different website; like a news org where our work got published? I know we may be able to hard code it in the home.hbs but having this linking ability in the template would be really helpful.

**Comment by jsoma** [comment]
That's great idea! So it's something we add to the YAML, yeah? Any
suggestions for formatting?

**Comment by fazilkhan** [comment]
Yeah, I think it'd be something we add to the YAML. I also think the formatting would mostly remain the same but it'll probably still take html as the type but instead of filepath it'll take an href URL to link the headline text on the homepage to an external webpage.

**Comment by jsoma** [comment]
You can see an example here: https://github.com/jsoma/bottlejack#using-datayaml
