### ISSUE TITLE
no such file or directory, open 'data.yaml' ????

### ISSUE THREAD

**Issue by alyssalukpat** [jsoma/bottlejack#6]
I followed the instructions in portfolio-autopublish up until it was time to publish. Then I ran bottlejack in the terminal and got this error: `Error: ENOENT: no such file or directory, open 'data.yaml'`
I saved the example folder on my desktop, where I also have the data.yaml file. What's going on?
![image](https://user-images.githubusercontent.com/23264666/119908047-b23a7900-bf1f-11eb-8cde-0c88af1f9399.png)

**Comment by jsoma** [comment]
Hm, are you running bottlejack in that folder? Give ls or pwd a shot and
make sure you're inside of the folder with data.yaml when you're running
the command.

**Comment by alyssalukpat** [comment]
thanks!
