### ISSUE TITLE
Customizable data.yaml

### ISSUE THREAD

**Issue by kaarnam** [jsoma/bottlejack#8]
Some clarity on what can be customized on the data.yaml page would be helpful. For example, if I wanted to add subtitles for each page, what do I need to do? Would I dabble with the default.css to style it?

**Comment by jsoma** [comment]
Added [some documentation for data.yaml](https://github.com/jsoma/bottlejack#using-datayaml) that should hopefully be helpful. Styling depends on the template you're working on!
