### ISSUE TITLE
Additional documentation for how to publish the site

### ISSUE THREAD

**Issue by sheridanwall** [jsoma/bottlejack#9]
Hi, I've followed the instructions on setting up the data.yaml page, but I'm a bit confused about how to actually publish the portfolio online. I ran the bottlejack command twice, and the first time I got an error message saying I need to open data.yaml. I tried running the command in a terminal window that I opened in my visual studio code and it returned a cli.js link, but I'm not sure what to do with that to move forward. I'm wondering if this would be something important to clarify in bottlejacks instructions, but I can also move the question over to Slack if not. Thank you!

**Comment by jsoma** [comment]
How about this? https://github.com/jsoma/bottlejack#publishing

**Comment by sheridanwall** [comment]
Thank you!
